### ISSUE TITLE
Page hanging when too many videos on same page at once.

### ISSUE THREAD

**Issue by Hez0** [riqpe/html5-youtube-everywhere#10]
Try loading this:
http://forums.smnnews.com/showthread.php?t=252771

Takes a while right? I have no idea whether this a normal limitation of what your extension is trying to do or whether there's a way around this, but I thought I'd give you a heads up anyway.

Cheers for the extension!

**Comment by rikusilvola** [comment]
The extension tries to replace all of  the embedded videos with iframes and as that forum has a huge amount of them on one page, it will take some time. More interesting is that it simply seems to fail for some of them later on on the page. I'll have to investigate this. Thanks for the report.

**Comment by rikusilvola** [comment]
On further inspection the ones not being replaced correctly are inserted dynamically with scripts. This functionality is at the moment not supported (see issue #9). As for the slowdown, unfortunately this is a side effect of how replacing a live node works. Future will show if I can improve on that. For now I'll close this issue.
