### ISSUE TITLE
Lag on youtube search results

### ISSUE THREAD

**Issue by Hez0** [riqpe/html5-youtube-everywhere#11]
This only appears to happen on search results (i.e., https://www.youtube.com/results?search_query=*), nowhere else. It appears that things within the results (i.e., yt3.ggpht.com; i.ytimg.com; s.ytimg.com) are loaded around a hundred times (according to uBlock) before the search results page is finished, causing a lot of lag, rendering the page unusable until it fully loads (~30 seconds).

This only happens when the addon is enabled. I can only image the page is loading all the videos in the search results twice, once via youtube and twice via the addon.

How can I blacklist youtube.com? Shouldn't it be blacklisted by default anyway?
I looked through about:config for any extension commands, on github and on the mozilla add-ons page and wasn't able to find out how to blacklist/whitelist.

Thanks once again for the extension.

Firefox 36.0.4.

**Comment by rikusilvola** [comment]
Hi Hez0,

First of all, thanks for reporting the issue here on GitHub. I'm currently backpacking in Vietnam, but I'll get on it once I'm back and have my hands on a proper computer. 

YouTube is indeed already blacklisted. Did you download the extension from AMO? The main branch  on GitHub is not in working state. Tag v0.5.2 corresponds to the current version on AMO.

Cheers.

**Comment by Hez0** [comment]
Yes, I got it from AMO and it's 0.5.2, but please, no need to respond until you get back.
You shouldn't even be looking at your e-mails, ya dingus!

**Comment by rikusilvola** [comment]
I've added the option to configure a blacklist. On AMO this feature is now in beta channel version 0.5.3b and the blacklist includes *.youtube.com by default. Current development of this feature happens in blacklist branch.

You can find the blacklist on about:config by searching for yt-blacklist. Both wildcard domains (*.domain.tld) and regexps (/.*domain.*/) can be used. Multiple items must be separated by commas (*.domain.tld, /.*domain.*/).

Adding YouTube to the blacklist improved responsiveness of the page you linked so if you have no objections, I'm closing this issue.

**Comment by Hez0** [comment]
I'm on 0.5.4b, and responsiveness on the youtube search page is indeed back to normal. Thank you so much for your work and hope Vietnam was great!
